name: Format
on:
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install Dependencies
              run: npm ci
            - name: Run Prettier Check
              run: npx prettier --check .
